version: 2.1
orbs:
  node: circleci/node@5.0.0
  nx: nrwl/nx@1.1.3
jobs:
  main:
    executor:
      name: node/default
      tag: 14.18.1
      
    steps:
      - checkout
      - run: yarn install
      - nx/set-shas
      - run: npx nx affected --base=$NX_BASE --target=build --parallel --max-parallel=3
      - run: npx nx affected --base=$NX_BASE --target=test --parallel --max-parallel=2
workflows:
  build:
    jobs:
      - main